### ISSUE TITLE
Site not reachable

### ISSUE THREAD

**Issue by ghost** [kbeckmann/ubuntu-openocd-git-builder#2]
Hello, I'm Matteo.

I am using a dockerfile that takes advantage of your repository.

Everything works fine, except when running your build.sh I get to line 16 "make openocd".

When the script tries to download the repository from "https://repo.or.cz/openocd.git" I get "Error 128" as the site is unreachable. In fact, even going from the browser to the address "https://repo.or.cz" the page does not load.

Is it a problem only mine and my connection / the state where I live (Italy) or did the site go down or was it closed?

Thanks in advance. Best regards,

Matteo

**Comment by kbeckmann** [comment]
It seems that the upstream repository is offline. You could change the
source to point to a GitHub mirror, e.g.
https://github.com/openocd-org/openocd

**Comment by ghost** [comment]
Ok thanks!
